### ISSUE TITLE
error while installing repo

### ISSUE THREAD

**Issue by mrhili** [PabVidCal/Angular7-Unsplash#1]
λ npm install

> node-sass@4.11.0 install C:\laragon\www\Projects\angularUnsplash\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/win32-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/win32-x64-72_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.11.0 postinstall C:\laragon\www\Projects\angularUnsplash\node_modules\node-sass
> node scripts/build.js

Building: C:\laragon\bin\nodejs\node-v12\node.exe C:\laragon\www\Projects\angularUnsplash\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\laragon\\bin\\nodejs\\node-v12\\node.exe',
gyp verb cli   'C:\\laragon\\www\\Projects\\angularUnsplash\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@12.5.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\laragon\www\Projects\angularUnsplash\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\laragon\www\Projects\angularUnsplash\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\laragon\www\Projects\angularUnsplash\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\laragon\www\Projects\angularUnsplash\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\laragon\www\Projects\angularUnsplash\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\laragon\www\Projects\angularUnsplash\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:165:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\laragon\www\Projects\angularUnsplash\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\laragon\www\Projects\angularUnsplash\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\laragon\www\Projects\angularUnsplash\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\laragon\www\Projects\angularUnsplash\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\laragon\www\Projects\angularUnsplash\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\laragon\www\Projects\angularUnsplash\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:165:21) {
gyp verb `which` failed   stack: 'Error: not found: python2\n' +
gyp verb `which` failed     '    at getNotFoundError (C:\\laragon\\www\\Projects\\angularUnsplash\\node_modules\\which\\which.js:13:12)\n' +
gyp verb `which` failed     '    at F (C:\\laragon\\www\\Projects\\angularUnsplash\\node_modules\\which\\which.js:68:19)\n' +
gyp verb `which` failed     '    at E (C:\\laragon\\www\\Projects\\angularUnsplash\\node_modules\\which\\which.js:80:29)\n' +
gyp verb `which` failed     '    at C:\\laragon\\www\\Projects\\angularUnsplash\\node_modules\\which\\which.js:89:16\n' +
gyp verb `which` failed     '    at C:\\laragon\\www\\Projects\\angularUnsplash\\node_modules\\isexe\\index.js:42:5\n' +
gyp verb `which` failed     '    at C:\\laragon\\www\\Projects\\angularUnsplash\\node_modules\\isexe\\windows.js:36:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:165:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\laragon\bin\python\python-3.6.1\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\laragon\bin\python\python-3.6.1\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:290:12)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:430:11)
gyp ERR! stack     at Socket.emit (events.js:200:13)
gyp ERR! stack     at Pipe.<anonymous> (net.js:588:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\laragon\\bin\\nodejs\\node-v12\\node.exe" "C:\\laragon\\www\\Projects\\angularUnsplash\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\laragon\www\Projects\angularUnsplash\node_modules\node-sass
gyp ERR! node -v v12.5.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1

> ngx-infinite-scroll@7.0.1 postinstall C:\laragon\www\Projects\angularUnsplash\node_modules\ngx-infinite-scroll
> opencollective postinstall

     *** Thank you for using ngx-infinite-scroll! ***

Please consider donating to our open collective
     to help us maintain this package.

  https://opencollective.com/ngx-infinite-scroll/donate

                    ***

npm WARN rollback Rolling back readable-stream@2.3.6 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\laragon\www\Projects\angularUnsplash\node_modules\fsevents\node_modules'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.11.0 (node_modules\node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.11.0 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 1075 packages from 1033 contributors and audited 1206 packages in 255.163s
found 2443 vulnerabilities (1805 low, 10 moderate, 627 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

C:\laragon\www\Projects\angularUnsplash (master)
λ npm install -h

npm install (with no args, in package dir)
npm install [<@scope>/]<pkg>
npm install [<@scope>/]<pkg>@<tag>
npm install [<@scope>/]<pkg>@<version>
npm install [<@scope>/]<pkg>@<version range>
npm install <folder>
npm install <tarball file>
npm install <tarball url>
npm install <git:// url>
npm install <github username>/<github project>

aliases: i, isntall, add
common options: [--save-prod|--save-dev|--save-optional] [--save-exact] [--no-save]

C:\laragon\www\Projects\angularUnsplash (master)
λ npm install

> node-sass@4.11.0 install C:\laragon\www\Projects\angularUnsplash\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/win32-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/win32-x64-72_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.11.0 postinstall C:\laragon\www\Projects\angularUnsplash\node_modules\node-sass
> node scripts/build.js

Building: C:\laragon\bin\nodejs\node-v12\node.exe C:\laragon\www\Projects\angularUnsplash\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\laragon\\bin\\nodejs\\node-v12\\node.exe',
gyp verb cli   'C:\\laragon\\www\\Projects\\angularUnsplash\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@12.5.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\laragon\www\Projects\angularUnsplash\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\laragon\www\Projects\angularUnsplash\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\laragon\www\Projects\angularUnsplash\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\laragon\www\Projects\angularUnsplash\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\laragon\www\Projects\angularUnsplash\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\laragon\www\Projects\angularUnsplash\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:165:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\laragon\www\Projects\angularUnsplash\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\laragon\www\Projects\angularUnsplash\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\laragon\www\Projects\angularUnsplash\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\laragon\www\Projects\angularUnsplash\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\laragon\www\Projects\angularUnsplash\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\laragon\www\Projects\angularUnsplash\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:165:21) {
gyp verb `which` failed   stack: 'Error: not found: python2\n' +
gyp verb `which` failed     '    at getNotFoundError (C:\\laragon\\www\\Projects\\angularUnsplash\\node_modules\\which\\which.js:13:12)\n' +
gyp verb `which` failed     '    at F (C:\\laragon\\www\\Projects\\angularUnsplash\\node_modules\\which\\which.js:68:19)\n' +
gyp verb `which` failed     '    at E (C:\\laragon\\www\\Projects\\angularUnsplash\\node_modules\\which\\which.js:80:29)\n' +
gyp verb `which` failed     '    at C:\\laragon\\www\\Projects\\angularUnsplash\\node_modules\\which\\which.js:89:16\n' +
gyp verb `which` failed     '    at C:\\laragon\\www\\Projects\\angularUnsplash\\node_modules\\isexe\\index.js:42:5\n' +
gyp verb `which` failed     '    at C:\\laragon\\www\\Projects\\angularUnsplash\\node_modules\\isexe\\windows.js:36:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:165:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\laragon\bin\python\python-3.6.1\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\laragon\bin\python\python-3.6.1\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:290:12)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\laragon\\bin\\nodejs\\node-v12\\node.exe" "C:\\laragon\\www\\Projects\\angularUnsplash\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\laragon\www\Projects\angularUnsplash\node_modules\node-sass
gyp ERR! node -v v12.5.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.11.0 (node_modules\node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.11.0 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

audited 1206 packages in 21.583s
found 2443 vulnerabilities (1805 low, 10 moderate, 627 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

C:\laragon\www\Projects\angularUnsplash (master)
λ npm audit fix
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.

> core-js@3.6.4 postinstall C:\laragon\www\Projects\angularUnsplash\node_modules\@angular-devkit\build-angular\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\rollup\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\rollup\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @angular-devkit/build-angular@0.901.6 requires a peer of @angular/compiler-cli@>=9.0.0 < 10 but none is installed. You must install peer dependencies yourself.
npm WARN @angular-devkit/build-angular@0.901.6 requires a peer of typescript@>=3.6 < 3.9 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@9.1.6 requires a peer of @angular/compiler-cli@>=9.0.0 < 10 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@9.1.6 requires a peer of typescript@>=3.6 < 3.9 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@8.0.2 requires a peer of node-sass@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@8.0.2 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-subresource-integrity@1.4.0 requires a peer of html-webpack-plugin@^2.21.0 || ~3 || >=4.0.0-alpha.2 <5 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @angular-devkit/build-angular@0.901.6
+ jquery@3.5.1
+ webpack-cli@3.3.11
added 652 packages from 188 contributors, removed 96 packages, updated 178 packages and moved 30 packages in 361.126s
fixed 2401 of 2443 vulnerabilities in 1206 scanned packages
  9 vulnerabilities required manual review and could not be updated
  5 package updates for 33 vulns involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)

C:\laragon\www\Projects\angularUnsplash (master)
λ npm install
npm WARN @angular-devkit/build-angular@0.901.6 requires a peer of @angular/compiler-cli@>=9.0.0 < 10 but none is installed. You must install peer dependencies yourself.
npm WARN @angular-devkit/build-angular@0.901.6 requires a peer of typescript@>=3.6 < 3.9 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@9.1.6 requires a peer of @angular/compiler-cli@>=9.0.0 < 10 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@9.1.6 requires a peer of typescript@>=3.6 < 3.9 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@8.0.2 requires a peer of node-sass@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@8.0.2 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-subresource-integrity@1.4.0 requires a peer of html-webpack-plugin@^2.21.0 || ~3 || >=4.0.0-alpha.2 <5 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\rollup\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 1703 packages in 17.553s
found 45 vulnerabilities (43 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details

C:\laragon\www\Projects\angularUnsplash (master)
λ npm audit fix --force
npm WARN using --force I sure hope you know what you are doing.
npm ERR! Unexpected end of JSON input while parsing near '...sSAnZWagAAzrkP/jTUwBa'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2020-05-15T01_16_01_258Z-debug.log

C:\laragon\www\Projects\angularUnsplash (master)

**Comment by mrhili** [comment]
UPDATING NPM TO v14 and still the error happen :



C:\laragon\www\Projects\angularUnsplash (master)
λ npm install

> node-sass@4.11.0 install C:\laragon\www\Projects\angularUnsplash\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/win32-x64-83_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/win32-x64-83_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.11.0 postinstall C:\laragon\www\Projects\angularUnsplash\node_modules\node-sass
> node scripts/build.js

Building: C:\laragon\bin\nodejs\node-v14.2.0\node.exe C:\laragon\www\Projects\angularUnsplash\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\laragon\\bin\\nodejs\\node-v14.2.0\\node.exe',
gyp verb cli   'C:\\laragon\\www\\Projects\\angularUnsplash\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.2.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\laragon\www\Projects\angularUnsplash\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\laragon\www\Projects\angularUnsplash\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\laragon\www\Projects\angularUnsplash\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\laragon\www\Projects\angularUnsplash\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\laragon\www\Projects\angularUnsplash\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\laragon\www\Projects\angularUnsplash\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:175:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\laragon\www\Projects\angularUnsplash\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\laragon\www\Projects\angularUnsplash\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\laragon\www\Projects\angularUnsplash\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\laragon\www\Projects\angularUnsplash\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\laragon\www\Projects\angularUnsplash\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\laragon\www\Projects\angularUnsplash\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:175:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\laragon\bin\python\python-3.6.1\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\laragon\bin\python\python-3.6.1\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:303:12)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:442:11)
gyp ERR! stack     at Socket.emit (events.js:315:20)
gyp ERR! stack     at Pipe.<anonymous> (net.js:671:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\laragon\\bin\\nodejs\\node-v14.2.0\\node.exe" "C:\\laragon\\www\\Projects\\angularUnsplash\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\laragon\www\Projects\angularUnsplash\node_modules\node-sass
gyp ERR! node -v v14.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1

> ngx-infinite-scroll@7.0.1 postinstall C:\laragon\www\Projects\angularUnsplash\node_modules\ngx-infinite-scroll
> opencollective postinstall


     *** Thank you for using ngx-infinite-scroll! ***

Please consider donating to our open collective
     to help us maintain this package.

  https://opencollective.com/ngx-infinite-scroll/donate

                    ***

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.11.0 (node_modules\node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.11.0 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 1075 packages from 1033 contributors and audited 1206 packages in 248.925s
found 2443 vulnerabilities (1805 low, 10 moderate, 627 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
